cdi/cdi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from shop.views import payment_cancelled, payment_done

urlpatterns = [
    path('jet/', include('jet.urls')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blogs/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-done/', payment_done, name='payment_done'),
    path('payment-cancelled/', payment_cancelled, name='payment_cancelled'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cdi/shop/urls.py
from django.contrib import admin
from django.urls import path, include


from .views import add_wishlist, home, product_detail, search, filter_data,\
    load_more_data, cart_list, delete_cart_item, update_cart_item, checkout, save_review, my_dashboard, my_orders, my_order_items,\
    add_wishlist, my_wishlist, my_reviews, my_addressbook, save_address, activate_address, update_address

app_name = 'shop'

urlpatterns = [
    path('', home, name='home'),
    path('<str:slug>/<int:_id>/', product_detail, name='product-detail'),
    path('search', search, name='search'),
    path('filter-data', filter_data, name='filter_data'),
    path('load-more-data', load_more_data, name='load_more_data'),
    path('cart', cart_list, name='cart'),
    path('delete-from-cart', delete_cart_item, name='delete_from_cart'),
    path('update-cart', update_cart_item, name='update_cart'),
    path('checkout', checkout, name='checkout'),
    path('save-review/<int:pid>', save_review, name='save_review'),
    # User Section Start
    path('my-dashboard', my_dashboard, name='my_dashboard'),
    path('my-orders', my_orders, name='my_orders'),
    path('my-order-items/<int:id>', my_order_items, name='my_order_items'),
    # End
    # Wishlist
    path('wishlist', add_wishlist, name='wishlist'),
    path('my-wishlist', my_wishlist, name='my_wishlist'),
    # My Reviews
    path('my-reviews', my_reviews, name='my_reviews'),
    # My AddressBook
    path('my-addressbook', my_addressbook, name='my_addressbook'),
    path('add-address', save_address, name='add_address'),
    path('activate-address', activate_address, name='activate_address'),
    path('update-address/<int:id>', update_address, name='update_address'),



]

cdi/shop/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=50, db_index=True, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at', )
        verbose_name = 'Category'
        verbose_name_plural = '1. Categories'

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=150, db_index=True, unique=True)
    image = models.ImageField(blank=True, null=True,
                              upload_to='images/brand_images/')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at', )
        verbose_name = 'Brand'
        verbose_name_plural = '2. Brands'

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % self.image.url)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100, db_index=True, unique=False)
    slug = models.CharField(max_length=400)
    description = models.TextField(max_length=800)
    specs = models.TextField(max_length=800)
    category = models.ForeignKey(
        Category, related_name='products', on_delete=models.CASCADE, blank=True, null=True)
    brand = models.ForeignKey(
        Brand, related_name='products', on_delete=models.CASCADE, blank=True, null=True)
    status = models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-created_at', )
        verbose_name_plural = '3. Products'


class ProductAttribute(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.PositiveIntegerField(blank=True, null=True)
    image_url1 = models.URLField(null=True)
    image_url2 = models.URLField(blank=True)
    image_url3 = models.URLField(blank=True)
    image_url4 = models.URLField(blank=True)

    class Meta:
        ordering = ('-id', )
        verbose_name_plural = '4. ProductsAttributes'

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % self.image_url1)

    def __str__(self):
        return self.product.name


# Order
status_choice = (
    ('process', 'In Process'),
    ('shipped', 'Shipped'),
    ('delivered', 'Delivered')
)


class CartOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total_amt = models.FloatField()
    paid_status = models.BooleanField(default=False)
    order_dt = models.DateTimeField(auto_now_add=True)
    order_status = models.CharField(
        max_length=150, choices=status_choice, default='process')

    class Meta:
        verbose_name_plural = '8. Orders'


# Order Items
class CartOrderItems(models.Model):
    order = models.ForeignKey(CartOrder, on_delete=models.CASCADE)
    invoice_no = models.CharField(max_length=150)
    item = models.CharField(max_length=150)
    image = models.CharField(max_length=200)
    qty = models.IntegerField()
    price = models.FloatField()
    total = models.FloatField()

    class Meta:
        verbose_name_plural = '9. Order Items'

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" />' % self.image)


# Product Review
RATING = (
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
)


class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    review_text = models.TextField()
    review_rating = models.CharField(max_length=150, choices=RATING)

    def get_review_rating(self):
        return self.review_rating

    class Meta:
        verbose_name_plural = 'Reviews'


# Wishlist
class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Wishlist'


# AdressBook
class UserAddressBook(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mobile = models.CharField(max_length=50, null=True)
    address = models.TextField()
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'AddressBook'

cdi/shop/forms.py
from django import forms
from django.db import models
from django.forms import fields

from .models import ProductReview, UserAddressBook


# Review Add Form
class ReviewAdd(forms.ModelForm):
    class Meta:
        model = ProductReview
        fields = ('review_text', 'review_rating')


# AddressBook Add Form
class AddressBookForm(forms.ModelForm):
    class Meta:
        model = UserAddressBook
        fields = ('address', 'mobile', 'status')

cdi/shop/views.py
import calendar
from django.contrib.auth import login
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from django.core.paginator import Paginator
from django.template.loader import render_to_string
from django.db.models import Max, Min, Avg, Count
from django.db.models.functions import ExtractMonth
from .models import Category, Brand, Product, ProductAttribute, CartOrder, CartOrderItems, ProductReview, Wishlist, UserAddressBook
from django.contrib.auth.decorators import login_required
from .forms import ReviewAdd, AddressBookForm

# paypal
from django.conf import settings

from django.urls import reverse

from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm


def home(request):
    products = Product.objects.all()[:3]
    total_data = Product.objects.count()
    min_price = ProductAttribute.objects.aggregate(Min('price'))
    max_price = ProductAttribute.objects.aggregate(Max('price'))
    feat_products = Product.objects.filter(is_featured=True)
    # paginator = Paginator(products, 9)
    # page_number = request.GET.get('page')
    # page_obj = paginator.get_page(page_number)
    context = {
        'title': 'Shop',
        'feat_products': feat_products,
        'products': products,
        'total_data': total_data,
        'min_price': min_price,
        'max_price': max_price,
    }
    return render(request, 'shop/home.html', context)


def product_detail(request, slug, _id):
    queryset = Product.objects.get(id=_id)
    related_products = Product.objects.filter(
        category=queryset.category).exclude(id=_id)[:4]

    reviewForm = ReviewAdd()

    canAdd = True
    reviewCheck = ProductReview.objects.filter(
        user=request.user, product=queryset).count()
    if request.user.is_authenticated:
        if reviewCheck > 0:
            canAdd = False

    reviews = ProductReview.objects.filter(product=queryset)

    # Fetch avg rating for reviews
    avg_reviews = ProductReview.objects.filter(
        product=queryset).aggregate(avg_rating=Avg('review_rating'))
    # End

    context = {
        'title': queryset.name,
        'data': queryset,
        'related_products': related_products,
        'form': reviewForm,
        'canAdd': canAdd,
        'reviews': reviews,
        'avg_reviews': avg_reviews

    }
    return render(request, 'shop/product-detail.html', context)


def search(request):
    q = request.GET['q']
    products = Product.objects.filter(name__icontains=q)
    total_data = products.count()
    # paginator = Paginator(products, 6)
    # page_number = request.GET.get('page')
    # page_obj = paginator.get_page(page_number)

    context = {
        'products': products,
        'total_data': total_data
    }
    return render(request, 'shop/search.html', context)


# Filter data
def filter_data(request):
    categories = request.GET.getlist('category[]')
    brands = request.GET.getlist('brand[]')
    min_price = request.GET['minPrice']
    max_price = request.GET['maxPrice']
    all_products = Product.objects.all().distinct()
    all_products = all_products.filter(productattribute__price__gte=min_price)
    all_products = all_products.filter(productattribute__price__lte=max_price)
    if len(categories) > 0:
        all_products = all_products.filter(
            category_id__in=categories).distinct()
    if len(brands) > 0:
        all_products = all_products.filter(brand_id__in=brands).distinct()
    t = render_to_string('shop/ajax/product-list.html', {'data': all_products})
    return JsonResponse({'data': t})


# Load More
def load_more_data(request):
    offset = int(request.GET['offset'])
    limit = int(request.GET['limit'])
    data = Product.objects.all().order_by('-id')[offset:offset + limit]
    t = render_to_string('shop/ajax/product-list.html', {'data': data})
    return JsonResponse({'data': t})


# Add to cart
def add_to_cart(request):
    # del request.session['cartdata']
    cart_p = {str(request.GET['id']): {
        'image': request.GET['image'],
        'name': request.GET['name'],
        'qty': request.GET['qty'],
        'price': request.GET['price'],
    }}
    if 'cartdata' in request.session:
        if str(request.GET['id']) in request.session['cartdata']:
            cart_data = request.session['cartdata']
            cart_data[str(request.GET['id'])]['qty'] = int(
                cart_p[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cartdata'] = cart_data
        else:
            cart_data = request.session['cartdata']
            cart_data.update(cart_p)
            request.session['cartdata'] = cart_data
    else:
        request.session['cartdata'] = cart_p
    return JsonResponse({'data': request.session['cartdata'], 'totalitems': len(request.session['cartdata'])})


# Cart List Page
def cart_list(request):
    total_amt = 0
    if 'cartdata' in request.session:
        for p_id, item in request.session['cartdata'].items():
            total_amt += int(item['qty']) * float(item['price'])
        context = {
            'title': 'Shopping Cart',
            'cart_data': request.session['cartdata'],
            'totalitems': len(request.session['cartdata']),
            'total_amt': total_amt
        }
        return render(request, 'shop/cart.html', context)

    else:
        context = {
            'title': 'Shopping Cart',
            'cart_data': '',
            'totalitems': 0,
            'total_amt': total_amt
        }
    return render(request, 'shop/cart.html', context)


# Delete Cart Item
def delete_cart_item(request):
    p_id = str(request.GET['id'])
    if 'cartdata' in request.session:
        if p_id in request.session['cartdata']:
            cart_data = request.session['cartdata']
            del request.session['cartdata'][p_id]
            request.session['cartdata'] = cart_data
    total_amt = 0
    for p_id, item in request.session['cartdata'].items():
        total_amt += int(item['qty']) * float(item['price'])
    t = render_to_string('shop/ajax/cart-list.html', {'cart_data': request.session['cartdata'],
                                                      'totalitems': len(request.session['cartdata']),
                                                      'total_amt': total_amt})
    return JsonResponse({'data': t, 'totalitems': len(request.session['cartdata'])})


# Update Cart Item
def update_cart_item(request):
    p_id = str(request.GET['id'])
    p_qty = request.GET['qty']
    if 'cartdata' in request.session:
        if p_id in request.session['cartdata']:
            cart_data = request.session['cartdata']
            cart_data[str(request.GET['id'])]['qty'] = p_qty
            request.session['cartdata'] = cart_data
    total_amt = 0
    for p_id, item in request.session['cartdata'].items():
        total_amt += int(item['qty'])*float(item['price'])
    t = render_to_string('shop/ajax/cart-list.html', {'cart_data': request.session['cartdata'],
                                                      'totalitems': len(request.session['cartdata']), 'total_amt': total_amt})
    return JsonResponse({'data': t, 'totalitems': len(request.session['cartdata'])})


# Checkout
@login_required
def checkout(request):

    total_amt = 0
    totalAmt = 0
    if 'cartdata' in request.session:
        for p_id, item in request.session['cartdata'].items():
            totalAmt += int(item['qty']) * float(item['price'])
        # Order
        order = CartOrder.objects.create(
            user=request.user,
            total_amt=totalAmt,
        )
        # End
        for p_id, item in request.session['cartdata'].items():
            total_amt += int(item['qty']) * float(item['price'])
            # OrderItems
            items = CartOrderItems.objects.create(
                order=order,
                invoice_no='INV-' + str(order.id),
                item=item['name'],
                image=item['image'],
                qty=item['qty'],
                price=item['price'],
                total=float(item['qty']) * float(item['price'])
            )
            # End
            host = request.get_host()
            paypal_dict = {
                'business': settings.PAYPAL_RECEIVER_EMAIL,
                'amount': total_amt,
                'item_name': 'OrderNo-' + str(order.id),
                'invoice': 'INV-' + str(order.id),
                'currency_code': 'USD',
                'notify_url': 'http://{}{}'.format(host, reverse('paypal-ipn')),
                'return_url': 'http://{}{}'.format(host, reverse('payment_done')),
                'cancel_return': 'http://{}{}'.format(host, reverse('payment_cancelled')),
            }
            form = PayPalPaymentsForm(initial=paypal_dict)
            address = UserAddressBook.objects.filter(
                user=request.user, status=True).first()
        context = {
            'title': 'Shopping Cart',
            'cart_data': request.session['cartdata'],
            'totalitems': len(request.session['cartdata']),
            'total_amt': total_amt,
            'form': form,
            'address': address
        }
        return render(request, 'shop/checkout.html', context)


@csrf_exempt
def payment_done(request):
    returnData = request.POST
    return render(request, 'shop/payment-success.html', {'data': returnData})


@csrf_exempt
def payment_cancelled(request):
    return render(request, 'shop/payment-fail.html')


# Save Review
def save_review(request, pid):
    product = Product.objects.get(pk=pid)
    user = request.user
    review = ProductReview.objects.create(
        user=user,
        product=product,
        review_text=request.POST['review_text'],
        review_rating=request.POST['review_rating'],
    )
    data = {
        'user': user.username,
        'review_text': request.POST['review_text'],
        'review_rating': request.POST['review_rating']
    }

    # Fetch avg rating for reviews

cdi/shop/templates/shop/cart.html
{% extends 'main/base2.html' %}
{% load static %}
{% block content2 %}
    <!-- Shoping Cart Section Begin -->
    <section class="shoping-cart spad" id="cartList">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__table">
                        <table>
                            <thead>
                                <tr>
                                    <th class="shoping__product">Products</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                 {% for product_id, item in cart_data.items %}
                                    <tr>
                                        <td class="shoping__cart__item">
                                            <img src="{{ item.image }}" alt="">
                                            <a href="{{ item.name|slugify }}/{{ product_id }}"><h3>{{ item.name }}</h3></a>
                                        </td>
                                        <td class="shoping__cart__price">
                                            ${{ item.price }}
                                        </td>
                                        <td class="shoping__cart__quantity">
                                            <div class="quantity">
                                                <div class="pro-qty">
                                                    <input type="text" class="product-qty-{{ product_id }}" value="{{ item.qty }}">
                                                </div>
                                            </div>
                                        </td>
                                        <td class="shoping__cart__total">
                                            ${% widthratio item.price 1 item.qty %}
                                        </td>
                                        <td class="shoping__cart__item__close">
                                            <button class="site-btn btn-success update-item"
                                                    data-item="{{ product_id }}">
                                                <i class="fa fa-sync fa-2x"></i>
                                            </button>
                                        </td>
                                        <td class="shoping__cart__item__close">
                                            <button class="site-btn btn-danger delete-item"
                                                    data-item="{{ product_id }}">
                                                <i class="fa fa-trash fa-2x"></i>
                                            </button>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__btns">
                        <a href="{% url 'shop:home' %}" class="primary-btn cart-btn">CONTINUE SHOPPING</a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="shoping__continue">
                        <div class="shoping__discount">
                            <h5>Discount Codes</h5>
                            <form action="#">
                                <input type="text" placeholder="Enter your coupon code">
                                <button type="submit" class="site-btn">APPLY COUPON</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="shoping__checkout">
                        <h5>Cart Total</h5>
                        <ul>
                            <li>Subtotal <span>$454.98</span></li>
                            <li>Total <span>${{ total_amt }}</span></li>
                        </ul>
                        <a href="#" class="site-btn">PROCEED TO CHECKOUT</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shoping Cart Section End -->
{% endblock content2 %}

cdi/shop/templates/shop/checkout.html
{% extends 'main/base2.html' %}
{% load static %}
{% block content2 %}
<!-- Shoping Cart Section Begin -->
<section class="shoping-cart spad" id="cartList">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="my-4 border-bottom pb-1">Cart Items: {{ totalitems }}</h3>
                <div class="shoping__cart__table">
                    <table>
                        <thead>
                            <tr>
                                <th class="shoping__product">Products</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for product_id, item in cart_data.items %}
                            <tr>
                                <td class="shoping__cart__item">
                                    <img src="{{ item.image }}" alt="">
                                    <a href="{{ item.name|slugify }}/{{ product_id }}">
                                        <h3>{{ item.name }}</h3>
                                    </a>
                                </td>
                                <td class="shoping__cart__price">
                                    ${{ item.price }}
                                </td>
                                <td class="shoping__cart__quantity">
                                    {{ item.qty }}
                                </td>
                                <td class="shoping__cart__total">
                                    ${% widthratio item.price 1 item.qty %}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="row">
                    <div class="col-md-9"></div>
                    <div class="col-md-3">
                        <h3 class="my-4 border-bottom pb-1">Selected Address</h3>
                        <div class="card">
                            <div class="card-body">
                                <p>{{ address.address }}</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="shoping__cart__btns">
                    <a href="{% url 'shop:home' %}" class="primary-btn cart-btn">CONTINUE SHOPPING</a>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="shoping__continue">
                    <div class="shoping__discount">
                        <h5>Discount Codes</h5>
                        <form action="#">
                            <input type="text" placeholder="Enter your coupon code">
                            <button type="submit" class="site-btn">APPLY COUPON</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="shoping__checkout">
                    <h5>Cart Total</h5>
                    <ul>
                        <li>Total <span>${{ total_amt }}</span></li>
                    </ul>
                    {{ form.render }}
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Shoping Cart Section End -->
{% endblock content2 %}

cdi/shop/templates/shop/payment-fail.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<main class="container my-4" id="cartList">
    <p>Payment Failed</p>
</main>
{% endblock %}

cdi/shop/templates/shop/payment-success.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<main class="container my-4" id="cartList">
    <p>Payment Success</p>
</main>
{% endblock %}

cdi/shop/templates/shop/search.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
    <!-- Product Section Begin -->
    <section class="product spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-5"></div>
                <div class="col-lg-9 col-md-7">
                    {% if products %}
                        <div class="product__discount">
                            <div class="section-title product__discount__title" style="margin-bottom: 0;">
                                <h2><span class="text-muted">Search result for: </span>{{ request.GET.q }}</h2>
                            </div>
                        </div>
                        <div class="filter__item">
                            <div class="row">
                                <div class="col-lg-4 col-md-5">
                                    <div class="filter__sort">
                                        <span>Sort By</span>
                                        <select>
                                            <option value="0">Default</option>
                                            <option value="0">Default</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4">
                                    <div class="filter__found">
                                        <h6 class="product_found"><span>{{ total_data }}</span> Product{{ total_data|pluralize }} found</h6>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-3">
                                    <div class="filter__option">
                                        <span class="icon_grid-2x2"></span>
                                        <span class="icon_ul"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            {% for data in products %}
                                <div class="col-lg-4 col-md-6 col-sm-6 product-box">
                                    <div class="product__item">
                                        <div class="product__item__pic set-bg">
                                            <img src="{{ data.productattribute_set.first.image_url1 }}" alt="">
                                            <ul class="product__item__pic__hover">
                                                <li><a href="#"><i class="fa fa-heart"></i><span>Wishlist</span></a></li>
                                                <li><a href="#"><i class="fa fa-eye"></i><span>View</span></a></li>
                                                <li><a href="#"><i class="fa fa-shopping-cart"></i><span>Cart</span></a></li>
                                            </ul>
                                        </div>
                                        <div class="product__item__text">
                                            <h6><a href="{{ data.slug }}/{{ data.id }}">{{ data.name }}</a></h6>
                                            <h5>${{ data.productattribute_set.first.price }}</h5>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <div class="product__discount">
                            <div class="section-title product__discount__title" style="margin-bottom: 0;">
                                <h2><span class="text-muted">No result for: </span>{{ request.GET.q }}</h2>
                                <hr>
                            </div>
                        </div>
                    {% endif %}
                    <div class="row justify-content-center">
                        <a href="{% url 'shop:home' %}" class="boxed-btn">All Products</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Product Section End -->
{% endblock content %}