cdi/blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import blog_list_view, blog_detail_view

app_name = 'blog'

urlpatterns = [
    path('', blog_list_view, name='blogs'),
    path('<int:_id>', blog_detail_view, name='blog-detail'),
]

cdi/cdi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from shop.views import payment_cancelled, payment_done

urlpatterns = [
    path('jet/', include('jet.urls')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blogs/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-done/', payment_done, name='payment_done'),
    path('payment-cancelled/', payment_cancelled, name='payment_cancelled'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cdi/blog/models.py
from django.db import models
from main.models import Section


class BlogModel(models.Model):
    blog_title = models.CharField(max_length=100)
    section = models.ForeignKey(
        Section, related_name='blogs', on_delete=models.CASCADE)
    blog = models.TextField()
    image = models.ImageField(blank=True, upload_to='images')
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_on = models.DateTimeField(auto_now_add=False, auto_now=True)

    class Meta:
        ordering = ('-timestamp', )
        verbose_name_plural = '1. BlogModels'

    def __str__(self):
        return self.blog_title


class CommentModel(models.Model):
    your_name = models.CharField(max_length=100)
    your_email = models.EmailField(max_length=254)
    comment_text = models.TextField()
    blog = models.ForeignKey('BlogModel', on_delete=models.CASCADE, related_name='commented_blog')
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-timestamp', )
        verbose_name_plural = '2. CommentModels'

    def __str__(self):
        return f'Comment by Name: {self.your_name}'

cdi/blog/forms.py
from django import forms
from .models import BlogModel


class CommentForm(forms.Form):
    your_name = forms.CharField(max_length=20)
    your_email = forms.EmailField(max_length=254)
    comment_text = forms.CharField(widget=forms.Textarea)

    def __str__(self):
        return f"{self.comment_text} by {self.your_name}"


class SearchForm(forms.Form):
    titleBlog = forms.CharField(max_length=20)


class SectionSearch(forms.ModelForm):
    class Meta:
        model = BlogModel
        fields = ['section']

cdi/blog/views.py
from django.http import Http404

from .models import BlogModel, CommentModel
from .forms import CommentForm, SearchForm, SectionSearch
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from main.models import Section


def blog_list_view(request):
    dataset = BlogModel.objects.all()
    sections = Section.objects.all()
    recent_posts = BlogModel.objects.all()[:4]
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            titleBlog = form.cleaned_data['titleBlog']
            dataset = BlogModel.objects.filter(blog_title__icontains=form['titleBlog'].value())
    else:
        form = SearchForm()

    if request.method == 'GET' and 'section' in request.GET:
        section_search = SectionSearch(request.GET)
        section = section_search['section'].value()
        dataset = BlogModel.objects.filter(section_id=section)
    else:
        section_search = SectionSearch()
    paginator = Paginator(dataset, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': 'Blog',
        'sections': sections,
        'page_obj': page_obj,
        'recent_posts': recent_posts,
        'form': form,
    }
    return render(request, 'blog/listview.html', context)


def blog_detail_view(request, _id):
    try:
        data = BlogModel.objects.get(id=_id)
        comments = CommentModel.objects.filter(blog=data)
        sections = Section.objects.all()
        recent_posts = BlogModel.objects.all()[:3]
    except BlogModel.DoesNotExist:
        raise Http404('Data does not exist')

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = CommentModel(your_name=form.cleaned_data['your_name'],
                                   your_email=form.cleaned_data['your_email'],
                                   comment_text=form.cleaned_data['comment_text'],
                                   blog=data)
            comment.save()
            return redirect(f'/blogs/{_id}')
    else:
        form = CommentForm()

    context = {
        'title': 'Blog Detail',
        'subtitle': f'Blog: {_id}',
        'data': data,
        'form': form,
        'sections': sections,
        'recent_posts': recent_posts,
        'comments': comments,
        'class': 'single-post-area'
    }
    return render(request, 'blog/detailview.html', context)

cdi/blog/templates/blog/blog_base.html
{% extends 'main/base2.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content2 %}
    <main>

        <!--? Blog Area Start-->
        <section class="blog_area {{ class }} section-padding">
            <div class="container">
                <div class="row">
                  {% block content3 %}

                  {% endblock content3 %}
                  <div class="col-lg-4">
                        <div class="blog_right_sidebar">
                            <aside class="single_sidebar_widget search_widget">
                                <form method="post" enctype="multipart/form-data">
                                    {%csrf_token %}
                                    <div class="form-group">
                                        <div class="input-group mb-3">
                                            <input name="titleBlog" type="text" class="form-control" placeholder='Search Title'
                                                onfocus="this.placeholder = ''"
                                                onblur="this.placeholder = 'Search Title'">
                                            <div class="input-group-append">
                                                <button class="btns" type="button"><i class="ti-search"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                    <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                        type="submit">Search</button>
                                </form>
                            </aside>
                            <aside class="single_sidebar_widget post_category_widget">
                                <h4 class="widget_title" style="color: #2d2d2d;">Sections</h4>
                                <ul class="list cat-list">
                                    <form method="get" enctype="multipart/form-data" name="section">
                                        {% for section in sections %}
                                            <li>
                                                <button value="{{ section.id }}" name="section" class="d-flex">
                                                    <p>{{ section.name }}
                                                        &nbsp;({{ section.blogs.all.count }} Article{{ section.blogs.all.count|pluralize }})</p>
                                                </button>
                                            </li>
                                        {% endfor %}
                                    </form>
                                </ul>
                            </aside>
                            <aside class="single_sidebar_widget popular_post_widget">
                                <h3 class="widget_title" style="color: #2d2d2d;">Recent Post</h3>
                                {% for recent_post in recent_posts %}
                                    <div class="media post_item">
                                        <img src="{{ recent_post.image.url }}" alt="post">
                                        <div class="media-body">
                                            <a href="{% url 'blog:blog-detail' recent_post.id %}">
                                                <h3 style="color: #2d2d2d;">{{ recent_post.blog_title }}</h3>
                                            </a>
                                            <p>{{ recent_post.timestamp|date:"F d, Y" }}</p>
                                        </div>
                                    </div>
                                {% endfor %}
                            </aside>
                            <aside class="single_sidebar_widget newsletter_widget">
                                <h4 class="widget_title" style="color: #2d2d2d;">Newsletter</h4>
                                <form action="#">
                                    <div class="form-group">
                                        <input type="email" class="form-control" onfocus="this.placeholder = ''"
                                            onblur="this.placeholder = 'Enter email'" placeholder='Enter email' required>
                                    </div>
                                    <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                        type="submit">Subscribe</button>
                                </form>
                            </aside>
                        </div>
                    </div>
                  </div>
                </div>
            </div>
        </section>
        <!-- Blog Area End -->
    </main>
{% endblock content2 %}

cdi/blog/templates/blog/detailview.html
{% extends 'blog/blog_base.html' %}
{% load static %}

{% block content3 %}
    <div class="col-lg-8 posts-list">
         <div class="single-post">
            <div class="feature-img">
               <img class="img-fluid" src="{{ data.image.url }}" alt="">
            </div>
            <div class="blog_details">
               <h2 style="color: #2d2d2d;">{{ data.blog_title }}</h2>
               <ul class="blog-info-link mt-3 mb-4">
                  <li><a href="#"><i class="fa fa-user"></i> {{ data.section }}</a></li>
                  <li><a href="#"><i class="fa fa-comments"></i> ({{ comments.count }} Comment{{ comments.count|pluralize }})</a></li>
               </ul>

               <div class="quote-wrapper">
                  <div class="quotes">{{ data.blog }}</div>
               </div>

            </div>
         </div>
         <div class="navigation-top">
            <div class="d-sm-flex justify-content-between text-center">
               <p class="like-info"><span class="align-middle"><i class="fa fa-heart"></i></span> Lily and 4
                  people like this</p>
               <div class="col-sm-4 text-center my-2 my-sm-0">
                  <!-- <p class="comment-count"><span class="align-middle"><i class="fa fa-comment"></i></span> 06 Comments</p> -->
               </div>
               <ul class="social-icons">
                  <li><a href="https://www.facebook.com/sai4ull"><i class="fab fa-facebook-f"></i></a></li>
                  <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                  <li><a href="#"><i class="fab fa-dribbble"></i></a></li>
                  <li><a href="#"><i class="fab fa-behance"></i></a></li>
               </ul>
            </div>
            <div class="navigation-area">
               <div class="row">
                  {% if data.get_previous_by_timestamp %}
                     <div
                        class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                        <div class="thumb">
                           <a href="{% url 'blog:blog-detail' data.get_previous_by_timestamp.id %}">
                              <img class="img-fluid" src="{{ data.get_previous_by_timestamp.image.url }}" alt="">
                           </a>
                        </div>
                        <div class="arrow">
                           <a href="{% url 'blog:blog-detail' data.get_previous_by_timestamp.id %}">
                              <span class="lnr text-white ti-arrow-left"></span>
                           </a>
                        </div>
                        <div class="detials">
                           <p>Prev Post</p>
                           <a href="{% url 'blog:blog-detail' data.get_previous_by_timestamp.id %}">
                              <h4 style="color: #2d2d2d;">{{ data.get_previous_by_timestamp.blog_title }}</h4>
                           </a>
                        </div>
                     </div>
                  {% endif %}
                  {% if data.get_next_by_timestamp %}
                     <div
                        class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                        <div class="detials">
                           <p>Next Post</p>
                           <a href="{% url 'blog:blog-detail' data.get_next_by_timestamp.id %}">
                              <h4 style="color: #2d2d2d;">{{ data.get_next_by_timestamp.blog_title }}</h4>
                           </a>
                        </div>
                        <div class="thumb">
                           <a href="{% url 'blog:blog-detail' data.get_next_by_timestamp.id %}">
                              <img class="img-fluid" src="{{ data.get_next_by_timestamp.image.url }}" alt="">
                           </a>
                        </div>
                        <div class="arrow">
                           <a href="{% url 'blog:blog-detail' data.get_next_by_timestamp.id %}">
                              <span class="lnr text-white ti-arrow-right"></span>
                           </a>
                        </div>
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
         <div class="blog-author">
            <div class="media align-items-center">
               <div class="media-body">
                  <a>
                     <h1><b>Comments Area</b></h1>
                  </a>
                  <p>You can read All blog comments and write other ones too</p>
               </div>
            </div>
         </div>
         <div class="comments-area">
            <h4>{{ comments.count }} Comment{{ comments.count|pluralize }}</h4>
            {% for comment in comments %}
               <div class="comment-list">
                  <div class="single-comment justify-content-between d-flex">
                     <div class="user justify-content-between d-flex">
                        <div class="thumb">
                           <img src="{% static 'main/assets/img/blog/comment_1.png' %}" alt="">
                        </div>
                        <div class="desc">
                           <p class="comment">{{ comment.comment_text }}</p>
                           <div class="d-flex justify-content-between">
                              <div class="d-flex align-items-center">
                                 <h5>
                                    <a href="#">{{ comment.your_name }}</a>
                                 </h5>
                                 <p class="date">{{ comment.timestamp|date:"F d, Y" }} at {{ comment.timestamp|date:"H:i" }} </p>
                              </div>
                              <div class="reply-btn">
                                 <a href="#" class="btn-reply text-uppercase">reply</a>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            {% endfor %}
         </div>
         <div class="comment-form">
            <h4>Leave a Comment</h4>
            <form method="post" class="form-contact comment_form" id="commentForm" enctype="multipart/form-data">
               {%csrf_token %}
               <div class="row">
                  <div class="col-12">
                     <div class="form-group">
                        <textarea class="form-control w-100" name="comment_text" id="comment" cols="30" rows="9"
                           placeholder="Type Your Comment" required></textarea>
                     </div>
                  </div>
                  <div class="col-sm-6">
                     <div class="form-group">
                        <input class="form-control" name="your_name" id="name" type="text" placeholder="Your Name" required>
                     </div>
                  </div>
                  <div class="col-sm-6">
                     <div class="form-group">
                        <input class="form-control" name="your_email" id="email" type="email" placeholder="Email">
                     </div>
                  </div>
               </div>
               <div class="form-group">
                  <button type="submit" class="button button-contactForm btn_1 boxed-btn">Post Comment</button>
               </div>
            </form>
         </div>
      </div>
{% endblock content3 %}

cdi/blog/templates/blog/listview.html
{% extends 'blog/blog_base.html' %}
{% load static %}

{% block content3 %}
    <div class="col-lg-8 mb-5 mb-lg-0">
        <div class="blog_left_sidebar">
            {% if page_obj %}
                {% for data in page_obj %}
                    <article class="blog_item">
                        <div class="blog_item_img">
                            <img class="card-img rounded-0" src="{{ data.image.url }}" alt="">
                            <a href="" class="blog_item_date">
                                <h3>{{ data.timestamp|date:"d" }}</h3>
                                <p>{{ data.timestamp|date:"F" }}</p>
                            </a>
                        </div>
                        <div class="blog_details">
                            <a class="d-inline-block" href="{% url 'blog:blog-detail' data.id %}">
                                <h2 class="blog-head" style="color: #2d2d2d;">{{ data.blog_title }}</h2>
                            </a>
                            <p>{{ data.blog }}</p>
                            <ul class="blog-info-link">
                                <li><a><i class="fa fa-cog"></i>{{ data.section }}</a></li>
                                <li><a href="#"><i class="fa fa-comments"></i>({{ data.commented_blog.count }} Comment{{ data.commented_blog.count|pluralize }})</a></li>
                            </ul>
                        </div>
                    </article>
                {% endfor %}
                <nav class="blog-pagination justify-content-center d-flex">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a href="?page=1" class="page-link" aria-label="Previous">First</a>
                            </li>
                        {% endif %}
                        {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num %}
                                <li class="page-item">
                                    <a href="?page={{ num }}" class="page-link" aria-label="Previous">{{ num }}</a>
                                </li>
                            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                <li class="page-item">
                                    <a href="?page={{ num }}" class="page-link" aria-label="Previous">{{ num }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Previous">Next</a>
                            </li>
                            <li class="page-item">
                                <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link" aria-label="Previous">Last</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% else %}
                <h1>No Blog Found.</h1>
            {% endif %}
        </div>
    </div>
{% endblock content3 %}